### PR TITLE
moving config.identifier to the begining of plugin output

### PR DESCRIPTION
**Pull request by snarf6**

### CODE REVIEW

**Comment by snarf6** [comment]
misclick from me, that should not be a PR so far :/

**Comment by sni** [comment]
no worries, just let me know when you are ready.

**Comment by snarf6** [comment]
back from holidays

this patch is running live here for about 2 months and nothing bad happend ;)

So, it's OK for me

**Comment by sni** [comment]
superseded by #33

this introduced an option to set it front or at the end.

**Pull request closed without merging**
